// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/gofermart/internal/services (interfaces: AccrualClient)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_accrual_client.go -package=mocks . AccrualClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SergeyRG/gofermart/internal/model"
	services "github.com/SergeyRG/gofermart/internal/services"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualClient is a mock of AccrualClient interface.
type MockAccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientMockRecorder
	isgomock struct{}
}

// MockAccrualClientMockRecorder is the mock recorder for MockAccrualClient.
type MockAccrualClientMockRecorder struct {
	mock *MockAccrualClient
}

// NewMockAccrualClient creates a new mock instance.
func NewMockAccrualClient(ctrl *gomock.Controller) *MockAccrualClient {
	mock := &MockAccrualClient{ctrl: ctrl}
	mock.recorder = &MockAccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClient) EXPECT() *MockAccrualClientMockRecorder {
	return m.recorder
}

// RequestAccrualSystemOrderStatus mocks base method.
func (m *MockAccrualClient) RequestAccrualSystemOrderStatus(ctx context.Context, orderID model.OrderID) (*services.AccrualSystemAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestAccrualSystemOrderStatus", ctx, orderID)
	ret0, _ := ret[0].(*services.AccrualSystemAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestAccrualSystemOrderStatus indicates an expected call of RequestAccrualSystemOrderStatus.
func (mr *MockAccrualClientMockRecorder) RequestAccrualSystemOrderStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestAccrualSystemOrderStatus", reflect.TypeOf((*MockAccrualClient)(nil).RequestAccrualSystemOrderStatus), ctx, orderID)
}
