// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/gofermart/internal/services (interfaces: AccrualService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_accrual_service.go -package=mocks . AccrualService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SergeyRG/gofermart/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualService is a mock of AccrualService interface.
type MockAccrualService struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualServiceMockRecorder
	isgomock struct{}
}

// MockAccrualServiceMockRecorder is the mock recorder for MockAccrualService.
type MockAccrualServiceMockRecorder struct {
	mock *MockAccrualService
}

// NewMockAccrualService creates a new mock instance.
func NewMockAccrualService(ctrl *gomock.Controller) *MockAccrualService {
	mock := &MockAccrualService{ctrl: ctrl}
	mock.recorder = &MockAccrualServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualService) EXPECT() *MockAccrualServiceMockRecorder {
	return m.recorder
}

// ChangeProcessingOrderStatus mocks base method.
func (m *MockAccrualService) ChangeProcessingOrderStatus(arg0 context.Context, arg1 model.OrderID, arg2 model.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeProcessingOrderStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeProcessingOrderStatus indicates an expected call of ChangeProcessingOrderStatus.
func (mr *MockAccrualServiceMockRecorder) ChangeProcessingOrderStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeProcessingOrderStatus", reflect.TypeOf((*MockAccrualService)(nil).ChangeProcessingOrderStatus), arg0, arg1, arg2)
}

// ProcessOrder mocks base method.
func (m *MockAccrualService) ProcessOrder(arg0 context.Context, arg1 model.OrderID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessOrder indicates an expected call of ProcessOrder.
func (mr *MockAccrualServiceMockRecorder) ProcessOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOrder", reflect.TypeOf((*MockAccrualService)(nil).ProcessOrder), arg0, arg1)
}

// SucceedOrder mocks base method.
func (m *MockAccrualService) SucceedOrder(arg0 context.Context, arg1 model.OrderID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SucceedOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SucceedOrder indicates an expected call of SucceedOrder.
func (mr *MockAccrualServiceMockRecorder) SucceedOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SucceedOrder", reflect.TypeOf((*MockAccrualService)(nil).SucceedOrder), arg0, arg1)
}
