// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/gofermart/internal/services (interfaces: BalanceRepo)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_balance_repo.go -package=mocks . BalanceRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SergeyRG/gofermart/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepo is a mock of BalanceRepo interface.
type MockBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoMockRecorder
	isgomock struct{}
}

// MockBalanceRepoMockRecorder is the mock recorder for MockBalanceRepo.
type MockBalanceRepoMockRecorder struct {
	mock *MockBalanceRepo
}

// NewMockBalanceRepo creates a new mock instance.
func NewMockBalanceRepo(ctrl *gomock.Controller) *MockBalanceRepo {
	mock := &MockBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepo) EXPECT() *MockBalanceRepoMockRecorder {
	return m.recorder
}

// AddOperation mocks base method.
func (m *MockBalanceRepo) AddOperation(arg0 context.Context, arg1 model.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOperation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOperation indicates an expected call of AddOperation.
func (mr *MockBalanceRepoMockRecorder) AddOperation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOperation", reflect.TypeOf((*MockBalanceRepo)(nil).AddOperation), arg0, arg1)
}

// AddUserBalance mocks base method.
func (m *MockBalanceRepo) AddUserBalance(arg0 context.Context, arg1 model.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserBalance indicates an expected call of AddUserBalance.
func (mr *MockBalanceRepoMockRecorder) AddUserBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserBalance", reflect.TypeOf((*MockBalanceRepo)(nil).AddUserBalance), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockBalanceRepo) GetByUserID(arg0 context.Context, arg1 model.UserID) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockBalanceRepoMockRecorder) GetByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockBalanceRepo)(nil).GetByUserID), arg0, arg1)
}

// GetWithdrawalsByUserID mocks base method.
func (m *MockBalanceRepo) GetWithdrawalsByUserID(arg0 context.Context, arg1 model.UserID) ([]model.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUserID", arg0, arg1)
	ret0, _ := ret[0].([]model.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUserID indicates an expected call of GetWithdrawalsByUserID.
func (mr *MockBalanceRepoMockRecorder) GetWithdrawalsByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUserID", reflect.TypeOf((*MockBalanceRepo)(nil).GetWithdrawalsByUserID), arg0, arg1)
}

// IncreaseBalance mocks base method.
func (m *MockBalanceRepo) IncreaseBalance(arg0 context.Context, arg1 model.UserID, arg2 model.MoneyQty) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseBalance", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseBalance indicates an expected call of IncreaseBalance.
func (mr *MockBalanceRepoMockRecorder) IncreaseBalance(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseBalance", reflect.TypeOf((*MockBalanceRepo)(nil).IncreaseBalance), arg0, arg1, arg2)
}

// ReduceBalance mocks base method.
func (m *MockBalanceRepo) ReduceBalance(arg0 context.Context, arg1 model.UserID, arg2 model.MoneyQty) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReduceBalance", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReduceBalance indicates an expected call of ReduceBalance.
func (mr *MockBalanceRepoMockRecorder) ReduceBalance(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReduceBalance", reflect.TypeOf((*MockBalanceRepo)(nil).ReduceBalance), arg0, arg1, arg2)
}
