// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/gofermart/internal/services (interfaces: BalanceService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_balance_service.go -package=mocks . BalanceService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SergeyRG/gofermart/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceService is a mock of BalanceService interface.
type MockBalanceService struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServiceMockRecorder
	isgomock struct{}
}

// MockBalanceServiceMockRecorder is the mock recorder for MockBalanceService.
type MockBalanceServiceMockRecorder struct {
	mock *MockBalanceService
}

// NewMockBalanceService creates a new mock instance.
func NewMockBalanceService(ctrl *gomock.Controller) *MockBalanceService {
	mock := &MockBalanceService{ctrl: ctrl}
	mock.recorder = &MockBalanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceService) EXPECT() *MockBalanceServiceMockRecorder {
	return m.recorder
}

// AddUserBalance mocks base method.
func (m *MockBalanceService) AddUserBalance(arg0 context.Context, arg1 model.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserBalance indicates an expected call of AddUserBalance.
func (mr *MockBalanceServiceMockRecorder) AddUserBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserBalance", reflect.TypeOf((*MockBalanceService)(nil).AddUserBalance), arg0, arg1)
}

// ExecOper mocks base method.
func (m *MockBalanceService) ExecOper(arg0 context.Context, arg1 model.Operation) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecOper", arg0, arg1)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecOper indicates an expected call of ExecOper.
func (mr *MockBalanceServiceMockRecorder) ExecOper(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecOper", reflect.TypeOf((*MockBalanceService)(nil).ExecOper), arg0, arg1)
}

// GetUserBalance mocks base method.
func (m *MockBalanceService) GetUserBalance(arg0 context.Context, arg1 model.UserID) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", arg0, arg1)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockBalanceServiceMockRecorder) GetUserBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockBalanceService)(nil).GetUserBalance), arg0, arg1)
}

// GetUserWithdrawals mocks base method.
func (m *MockBalanceService) GetUserWithdrawals(ctx context.Context, userID model.UserID) ([]model.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]model.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockBalanceServiceMockRecorder) GetUserWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockBalanceService)(nil).GetUserWithdrawals), ctx, userID)
}
