// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/gofermart/internal/services (interfaces: OrderService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_order_service.go -package=mocks . OrderService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	model "github.com/SergeyRG/gofermart/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockOrderService) AddOrder(arg0 context.Context, arg1 model.UserID, arg2 model.OrderID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockOrderServiceMockRecorder) AddOrder(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockOrderService)(nil).AddOrder), arg0, arg1, arg2)
}

// ChangeOrderStatus mocks base method.
func (m *MockOrderService) ChangeOrderStatus(arg0 context.Context, arg1 model.OrderID, arg2 model.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeOrderStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeOrderStatus indicates an expected call of ChangeOrderStatus.
func (mr *MockOrderServiceMockRecorder) ChangeOrderStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeOrderStatus", reflect.TypeOf((*MockOrderService)(nil).ChangeOrderStatus), arg0, arg1, arg2)
}

// GetByIDForUpdate mocks base method.
func (m *MockOrderService) GetByIDForUpdate(ctx context.Context, oID model.OrderID) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, oID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockOrderServiceMockRecorder) GetByIDForUpdate(ctx, oID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockOrderService)(nil).GetByIDForUpdate), ctx, oID)
}

// GetNextOrderIDForProcessing mocks base method.
func (m *MockOrderService) GetNextOrderIDForProcessing(ctx context.Context) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextOrderIDForProcessing", ctx)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextOrderIDForProcessing indicates an expected call of GetNextOrderIDForProcessing.
func (mr *MockOrderServiceMockRecorder) GetNextOrderIDForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextOrderIDForProcessing", reflect.TypeOf((*MockOrderService)(nil).GetNextOrderIDForProcessing), ctx)
}

// GetUserOrders mocks base method.
func (m *MockOrderService) GetUserOrders(arg0 context.Context, arg1 model.UserID) iter.Seq2[*model.Order, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", arg0, arg1)
	ret0, _ := ret[0].(iter.Seq2[*model.Order, error])
	return ret0
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrderServiceMockRecorder) GetUserOrders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrderService)(nil).GetUserOrders), arg0, arg1)
}

// UpdateOrder mocks base method.
func (m *MockOrderService) UpdateOrder(ctx context.Context, o model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderServiceMockRecorder) UpdateOrder(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderService)(nil).UpdateOrder), ctx, o)
}
